### ISSUE TITLE
Informació de API de registre

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/instanciagenerica#11]
Desde l'aplicació que esteim desenvolupant, necessitam atacar a registre per donar d'alta una instancia genèrica. 

Ens fa falta saber:
1. La dependencia MAVEN necesaria
2. Dades de conexió a registre de Fundació BIT
3. Un exemple de com es crida a l'API

**Comment by mgonzalez-fundaciobit** [comment]
Enviada info per email.
