### ISSUE TITLE
Exportar script de creació de BBDD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#16]
Anar a PgAdminIII i exportar el schema de la BBDD de instancia generica en format SQL. Guardar-ho a scripts/bbdd/postgresql i commitar-ho.

**Comment by ptrias-fundaciobit** [comment]
Fet:
![image](https://user-images.githubusercontent.com/95921330/152492260-6ea44d10-d283-4d5c-8534-b05a57b7e3eb.png)
