### ISSUE TITLE
El jsp menu_admin.jsp no s'ha commitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#18]
El jsp menu_admin.jsp no s'ha commitat

![imagen](https://user-images.githubusercontent.com/17084256/152773513-e9c5591d-0bd6-4729-803b-161205359d49.png)

**Comment by ptrias-fundaciobit** [comment]
A algún moment, s'han borrat sense voler menu_admin.jsp i menu_user.jsp. no se perque ha passat, pero he tornat a fer el menu_admin.jsp amb el menu de llistats. 

Com que no s'emplea el menu_user.jsp per res, no l'he fet, ja el faré si fos necessari.
![image](https://user-images.githubusercontent.com/95921330/152795436-6c319138-8fd4-41fa-9e23-47e300e9cfa8.png)
