### ISSUE TITLE
Millorar el Menú de canvi d'Idioma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#19]
Millorar el Menú de canvi d'Idioma: 
* Posar les etiquetes dels idiomes
* No mostrar Anglès.

![imagen](https://user-images.githubusercontent.com/17084256/152804475-b0806eb5-cd42-4014-8346-f59d973bcc47.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/153397059-c9373b4c-b8d7-4cf3-9053-026111475e85.png)
![image](https://user-images.githubusercontent.com/95921330/153397104-26b93631-ea04-4b1c-ba78-60f8790b8001.png)
