### ISSUE TITLE
Crear readme.md

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/instanciagenerica#2]
Crear el document readme.md similar al que hi ha a:

https://github.com/GovernIB/genapp/edit/master/README.md

**Comment by ptrias-fundaciobit** [comment]
Está ja el readme modificat

**Comment by anadal-fundaciobit** [comment]
Falta el readme.md de https://github.com/Fundacio-Bit/instanciagenerica/tree/instanciagenerica-1.0

**Comment by ptrias-fundaciobit** [comment]
Ja estan el dos readme modificats. També he possat el logo que estic empleant per la webapp:
![image](https://user-images.githubusercontent.com/95921330/151555804-a8179eba-27ec-4405-a56f-c416bbcea478.png)

**Comment by anadal-fundaciobit** [comment]
Aquest aplicació no és per la CAIB, és  pel registre de la FundacióBit: Recorda que has de pensar amb el cas de quan tu vares venir a registrar la teva preinscripció.
