### ISSUE TITLE
Millores en Peu de Llistat i en el Footer

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#20]
(1) Afegir al div el style "text-align:left"
(2) Afegir al div la classe css "text-left"
(3) Afegir al div el style "text-align:right"
(4) Eliminar tags <center> i afegir   classe css "text-right"

(5) Al layout.jsp, el tag que inclou el "peu" se li han de canviar les classes css "container row-fluid" per "container-fluid"

![imagen](https://user-images.githubusercontent.com/17084256/152942086-48783a76-ea5e-46bd-a425-9696b4ae3bd7.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/158158608-44da8b60-33a9-4f7c-afa1-af25ed5f47ce.png)
