### ISSUE TITLE
Millores en la pantalla de Instancies generiques no registrades

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#21]
Millores en en la pantalla de Instancies generiques no registrades:

(1) No mostrar columna "Numero de registre"
(2) Ajuntar columna "Data de Creacio´" i "Data Finalització"
(3) Canviar Label (addLabel()) de Data Finalització per "Data Error"

![imagen](https://user-images.githubusercontent.com/17084256/152943270-46659881-19e8-4bbc-9433-9e8b5b1b6919.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/153403262-045496b6-7e70-4a89-9463-f2414f329c1c.png)

**Comment by anadal-fundaciobit** [comment]
Falta canviar l'ordre de les dates:
     * Moure Data Creació despres de correu electronic
     * Moure Data Error posar-la abans de "Error"

No has de tocar codi. tot es fa amb GenApp.

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/153405460-23430d1d-0373-4b78-a9ee-0ac0bc0c30f0.png)
