### ISSUE TITLE
Pàgina de Detalls del Registre i arreglar pipelles

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/instanciagenerica#23]
(1) Canviar el nom de la Pipella "LLISTATS" per "Menú Administrador"
(2) Recuperar Pipella de User i  llevar opcions del menu.

(3) A la llista de Instancies genèriques afegir un boto a cada opció per veure els detalls del Registre:
             (a) Si no te Numero de registre tornar al llistat i mostrar un error
             (b) Cridar a ObtenerAsientoRegistral()
             (c) Crear un JSP que mostri les dades obtingudes del punt (b)

    Aquest JSP ha de ser senzill, una taula on en cada fila posar un camp de l'objecte obtingut.

**Comment by ptrias-fundaciobit** [comment]
Fet:
![image](https://user-images.githubusercontent.com/95921330/154230551-03bfd622-74fc-46a4-9d0a-4a5bfb372ce4.png)
