### ISSUE TITLE
Millora de header i footer del back

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/instanciagenerica#4]
Header: 
 -llevar logo
 - usuari null|null
 
Footer:
 - Arreglar ajuda
 - Llevar MAPA WEB, etc

**Comment by ptrias-fundaciobit** [comment]
Modificats header i footer:
![image](https://user-images.githubusercontent.com/95921330/151346605-3012c5d2-c4d1-4102-8923-41afb0676167.png)
![image](https://user-images.githubusercontent.com/95921330/151346640-6ff246c2-0008-4dd0-89b4-32644d433774.png)

**Comment by anadal-fundaciobit** [comment]
(0) No està definit Milestone
(1) No està fet lo de l'usuari null:nulll
(2) L'ajuda: telefon de la fundació bit, web de la fundaciobit, i email de otae@fundaciobit.org
(3) Baixar logo en gris de la fundació que es troba al peu a la dreta (esta aferrat a la linia)

**Comment by ptrias-fundaciobit** [comment]
Ja está modificat tot:
![image](https://user-images.githubusercontent.com/95921330/151356755-f472d328-ee77-43f9-8ec5-a2ea5ed3a8bb.png)
![image](https://user-images.githubusercontent.com/95921330/151356842-748c9347-f6ec-43c0-82ca-315b6d2b5032.png)
![image](https://user-images.githubusercontent.com/95921330/151356921-2d1ddbd0-ddc1-4462-959d-46e31cfa7a7f.png)

**Comment by anadal-fundaciobit** [comment]
Falta: 
(1) Numero telefon de la funcació és el que surt a la pàgina web de la fundaciobit
(2) Enlloc de "usuari no registrat" NO ha de posar res.


![imagen](https://user-images.githubusercontent.com/17084256/151357821-757e885c-5bf3-45fa-8997-46ba25639c11.png)

**Comment by ptrias-fundaciobit** [comment]
Ja está arreglat!
![image](https://user-images.githubusercontent.com/95921330/151362874-ac9f1358-a5d4-4242-9e0e-72ba1356692f.png)
